### ISSUE TITLE
Domain_ID = Metadata, Vocabulary_ID = Relationship

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#111]
We would like to request a new relationship CONCEPT_ID called "Linked To"

**Comment by cgreich** [comment]
What does that mean, linked to? Linked how?

**Comment by ericaVoss** [comment]
At ERASMUS we have this concept of linked data.  Essentially they review notes for conditions and drugs.  The conditions/drugs then get added to CONDITION_OCCURRENCE/DRUG_EXPOSURE/OBSERVATION and they want to be able to link those entries to the actual NOTE.  We'll used the FACT_RELATIONSHIP to tie the records and wanted an appropriate RELATIONSHIP_CONCEPT_ID to describe the relationship.  Otherwise we'll just use 0 if you don't want to add this.

**Comment by cgreich** [comment]
Should we introduce something like "Derived from" and "Used to derive"?

**Comment by marcel1334** [comment]
"Derived from" will be a good and useful extra term for the vocab. But unfortunately not usable for our situation. In our IPCI database we simple have a link between conditions and other kinds of data. The context of the link is unknown but and we want to keep this link. Sometimes it will be an incoming letter from a specialist resulting in a condition record that is derived from this letter. In this case the "Derived from" will be a correct link. But unfortunately we don't have this context. It can also be a letter from the fundus checkup for a diabetes patient that is linked to the condition diabetes. In this case we can not say the this diabetes is derived from this letter about the retinopathia. 
Another example is a patient that has a visit for diabetes care. This consult can result in various notes, measurements, referrals and prescriptions. And these records will all be linked to the condition diabetes. And in the same consult we can have a extra prescription for COPD and that one will be linked to the condition COPD.

So that is why we are looking for a kind of generic relationship. The other option is to use the 0=unknown value for the relationship.

**Comment by cgreich** [comment]
Probably is better to discuss this in the Forum. Want to do that?

**Comment by ericaVoss** [comment]
I'm closing this as I'm sure we have already created a solution.
