### ISSUE TITLE
Make Cost_types standard again

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#190]
The concept_ids 5031, 5032, 5033 have been moved to non-standard but I think they should be switched back to standard. There are 6 Cost Type concepts but the three that are standard do not adequately represent all cost types exist. They are:
 1) Payer is primary (coordination of benefit) 
 2) Payer is secondary (coordination of benefit) 
 3) Premium

These do not cover costs that are billed by providers or paid by patients, they only cover costs that are outgoing from the payer or are considered premiums.

**Comment by cgreich** [comment]
Do you remember why we killed them in January?

**Comment by gowthamrao** [comment]
Concept_id | Concept_name
-- | --
5031 | Cost incurred by the provider
5032 | Amount paid by the patient or reimbursed by the payer
5033 | Amount charged to the patient or the payer by the provider, list price

**Here are some explanations as to why they were made non standard:** Mostly because they were 'dirty concepts', and the new CDM 6.+ cost table allowed for more specific cost concepts.

**5032  Amount paid by the patient or reimbursed by the payer** - this concept is ambiguous. i.e. it represents two concepts.
If paid by patient -- the options for cost_concept_id may be 32420 Patient liability or 31981 Out of Pocket. If this data came from a payer's claim system (coordination of benefits) then cost_type_concept_id maybe 31968 or 31969 depending on if the payer is primary or payer is secondary
If reimbursed. If it came from EHR we would need a cost_type_concept_id to represent that.
If reimbursed by the payer -- the cost_type_concept_id of 31968, 31969. For cost_concept_id we would have 31980 Paid

**5033  Amount charged to the patient or the payer by the provider, list price** This concept represents what a provider would like to charge for a service. We have cost_concept_id = 31973. For cost_type_concept_id it maybe 31968 or 31969 if claims system. We may need new type concept id .

**5031 Cost incurred by the provider**: Implies the cost to provide care by the provider. This may be representation of cost components like drug/device procurement, clinician labor costs, facility overhead, regulatory expenses etc., and may be part of a hospital/clinics financial systems. 
For this case we would need a Cost_type concept id to indicate the provenance of the data, maybe a new concept like 'Provider billing' to be used cost.cost_type_concept_id. For cost.cost_concept_id, one option may be 'Net costs' or 'Gross costs' depending on how it interpreted.

**Comment by gowthamrao** [comment]
Concept_id | Concept_name
-- | --
5031 | Cost incurred by the provider
5032 | Amount paid by the patient or reimbursed by the payer
5033 | Amount charged to the patient or the payer by the provider, list price

These were originally **'Type concept'** for cost, and we needed to clean them up. The new CDM 6+ cost tables has both cost_concept_id and cost_type_concept_id - and I think we need more specific type concepts to help with the provenance of the cost data. Currently they mostly support payer claims data based provenance, does not support EHR/billing system - for billed by providers etc. Reinstating these Type concepts as standard may be a good stop gap.

**Comment by gowthamrao** [comment]
I think what @clairblacketer is saying is that we need appropriate Type Concepts for use in the field cost.cost_type_concept_id of the CDM 6.+ cost table that represents provenance such as 

- derived from a payers administrative claims data
- derived from electronic health record billing system
- self reported by the person/patient

Currently we only have three type concepts that are appropriate for administrative claims data. We dont have type-concepts that are appropriate for self reported or EHR billing system provenance.

Concept Id | Code | Name | Class | Domain | Vocabulary
-- | -- | -- | -- | -- | --
31970 | OMOP   generated | Premium | Type   Concept | Type   Concept | Cost   Type
31968 | OMOP   generated | Payer   is primary (coordination of benefit) | Type   Concept | Type   Concept | Cost   Type
31969 | OMOP   generated | Payer   is secondary (coordination of benefit) | Type   Concept | Type   Concept | Cost   Type

**Comment by clairblacketer** [comment]
Based on the original proposal [#81](https://github.com/OHDSI/CommonDataModel/issues/81#issuecomment-324651946) the cost type concepts needed are: 

- Copayment amount
- Coinsurance amount
- Charged by the provider
- Recovered by the provider
- Allowed by the primary payer
- Paid by the primary payer
- Allowed by the secondary payer
- Paid by the secondary payer
- Allowed by all payers
- Paid by all payers
- Charged to the patient
- Paid by the patient total out of pocket
- Paid by the patient towards co-insurance
- Paid by the patient towards copay
- Paid by the patient towards deductible
- Fee for pharmacy dispensing
- Cost of pharmacy ingredient
- Average Wholesale Price amount

**Comment by gowthamrao** [comment]
@clairblacketer

I am little confused here, especially because we seem to be mixing up cost_type_concept_id and cost_concept_id

We have good cost_concept_id's 
Summary costs: http://athena.ohdsi.org/search-terms/terms?domain=Cost&standardConcept=Standard&conceptClass=Summary&vocabulary=Cost&invalidReason=Valid&page=1&pageSize=15&query=
Detail costs: http://athena.ohdsi.org/search-terms/terms?domain=Cost&standardConcept=Standard&conceptClass=Detail&vocabulary=Cost&invalidReason=Valid&page=1&pageSize=15&query=


We need better cost_type_concept_id
http://athena.ohdsi.org/search-terms/terms?domain=Type+Concept&standardConcept=Standard&conceptClass=Type+Concept&page=1&pageSize=15&query=

**Comment by ericaVoss** [comment]
@gowthamrao & @cgreich  & @aostropolets  & @dimshitc , 

Are these slated to be added to the Vocab any time soon - we are going to V6 soon and like to have these ready for when we work on that

**Comment by dimshitc** [comment]
So what do we need, to add these 3 concepts:
Billing system (Electronic Health Record)
Bills (Reported by person)
Payments (Reported by person),
nothing else, right?

**Comment by dimshitc** [comment]
done
