### ISSUE TITLE
Suspicious NDCs

### ISSUE THREAD

**Issue by abedtashh** [OHDSI/Vocabulary-v5.0#223]
RxNav says these NDCs are Acyclovir, but they are Leuprolide in OMOP. Can you please double-check if these are correct? Thanks!

NAME | CLASS ID | CODE
-- | -- | --
0.375 ml leuprolide acetate 120 mg/ml prefilled syringe [eligard] | 11-digit NDC | 53873099404
0.375 ml leuprolide acetate 120 mg/ml prefilled syringe [eligard] | 11-digit NDC | 53873099406
0.375 ml leuprolide acetate 120 mg/ml prefilled syringe [eligard] | 11-digit NDC | 53873099407
0.375 ml leuprolide acetate 120 mg/ml prefilled syringe [eligard] | 11-digit NDC | 64455099419
0.375 ml leuprolide acetate 120 mg/ml prefilled syringe [eligard] | 11-digit NDC | 64455099420

**Comment by abedtashh** [comment]
Hi @aostropolets, appreciate any updates on this. Thanks!

**Comment by abedtashh** [comment]
@Alexdavv Hi, would be great if these NDCs could be validated before the next vocab release. RxNav identifies these NDCs as Acyclovir products, for example: [53873099404](https://mor.nlm.nih.gov/RxNav/search?searchBy=NDC&searchTerm=53873099404)

**Comment by Alexdavv** [comment]
@abedtashh thanks for the catch.

I've tested the NDC_SPL load_stage against these 5 particular NDCs codes. The issue is:
- They do not come from the official NDC files but from the **rxnav.nlm.nih.gov** [here](https://github.com/OHDSI/Vocabulary-v5.0/blob/470aa13cb1b71882bbc02a24479cdfd3818b1dab/NDC_SPL/load_stage.sql#L792).
- The mappings are taken from the **rxnav.nlm.nih.gov** and considered to be correct.
- But the concept_name is [taken](https://github.com/OHDSI/Vocabulary-v5.0/blob/470aa13cb1b71882bbc02a24479cdfd3818b1dab/NDC_SPL/load_stage.sql#L778) from the concept table (option 2 by COALESCE).

I am assuming that while populating this portion of the NDC vocabulary we use the concept_name previously originated from some static NDC source containing wrong concept_names.
@aostropolets Is there a way to track the source these concept_names are taken from?

**Comment by aostropolets** [comment]
Interesting thing. Should be Acyclovir indeed and the mapping is correct (so in terms of standard mappings it shouldn't be an issue). Will see where it's coming from

**Comment by Alexdavv** [comment]
Except for NDC 00002824001 'Insulin, Regular, Beef-Pork 40 UNT/ML Inhalant Solution',
the same wrong naming issues are [this](https://github.com/OHDSI/Vocabulary-v5.0/issues/218#issue-431644132) and [this](https://github.com/OHDSI/Vocabulary-v5.0/issues/218#issuecomment-487327899).

Another thing is NDC 00002824001 'Insulin, Regular, Beef-Pork 40 UNT/ML **Inhalant Solution**'. RxNav [maps ](https://mor.nlm.nih.gov/RxNav/search?searchBy=NDC&searchTerm=00002824001)it to RxNorm 311055 saying this is 'Insulin, Regular, Beef-Pork 40 UNT/ML **Inhalant Solution**'.

The problem is CDM vocabularies recognize RxNorm 311055 as 'insulin, regular, beef-pork 40 UNT/ML **Injectable Solution**' including the link to a form of 19082103 **Injectable Solution**.
@aostropolets Any ideas?

**Comment by aostropolets** [comment]
Interesting. I've no idea why this type of error occurs, which means that it will require more time to investigate it.

**Comment by Alexdavv** [comment]
> Another thing is NDC 00002824001 'Insulin, Regular, Beef-Pork 40 UNT/ML **Inhalant Solution**'. RxNav [maps ](https://mor.nlm.nih.gov/RxNav/search?searchBy=NDC&searchTerm=00002824001)it to RxNorm 311055 saying this is 'Insulin, Regular, Beef-Pork 40 UNT/ML **Inhalant Solution**'.

In one of the releases, RxNorm updated the dose form to correct one.
Is there any evidence that NDC 00002824001 had really inhalant form?
