### ISSUE TITLE
Not all concept names are also concept synonyms

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#25]
Not sure if this is by design. For example, none of the UCUM concepts appear in the synonym table.

**Comment by cgreich** [comment]
Because we only introduced that now. The next release will have it.

Speaking off, Martijn: I will remove the synonyms you built for SNOMED. Becasue it is the UMLS way to cross many concepts. We don't support "downwards" equivalents from SNOMED. But you will get the true SNOMED synonyms. You may want to adjust Usagi.

**Comment by schuemie** [comment]
No worries, I will use whatever you choose to put in the concept_synonym table

**Comment by cgreich** [comment]
Closed
