### ISSUE TITLE
improve HemOnc documentation

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/Vocabulary-v5.0#257]
https://github.com/OHDSI/Vocabulary-v5.0/tree/master/HemOnc

link to recent Recent JBI paper would be great too.

**Comment by vladkorsik** [comment]
@vojtechhuser pretty old,  but for some reason  not closed issue. We usually  put vocabulary related information relevant for it's usage at [Standardized Vocabularies page ](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Standardized-Vocabularies) and [vocabulary release notes page](https://github.com/OHDSI/Vocabulary-v5.0/releases)
NB! Since the introduction of HemOnc specifications in 2021, [here ](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Vocab.-HemOnc)you can find a little update for it.
