### ISSUE TITLE
DRG Dates

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#26]
DRGs are a date related VOCAB, but all the dates seem to be the same in the VOCAB. How do I associate the proper DRG to the time period of interest?  

You can also know differences by the version of the DRG vocab, but not sure if that is easy to integrate.

**Comment by cgreich** [comment]
Erica:

1. I fixed the concept classes. There is now DRG and MS-DRG. You need that because the codes overlap but are completely different.
2. There are relationships between them, btw.
3. Within DRG and MS-DRG you need to go by valid_start_date and valid_end_date. For each code, there are multiple concepts (violating the rules). 

For example, for DRG code 001 (Craniotomy) you got a concept from 01-OCT-94 to 30-SEP-02 and another one from 01-OCT-02 to 30-SEP-07. There is a MS-DRG concept 001 (Heart transplant) from 01-OCT-07 to 31-DEC-99.

I haven't updated them in this release. Will put on list of things.

**Comment by cgreich** [comment]
Fixed.
