### ISSUE TITLE
Puncture of Vessel descendant of Surgical procedure on soft tissue

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#273]
The concept _puncture of vessel_ (4053719) is a descendant of _surgical procedure on soft tissue_ (4159949). This means that _venipuncture_ (4332170) and _venipuncture for blood test_ (4102442) become descendants of _surgical procedure_ (4301351). I am not sure this makes sense, should venipuncture be considered a surgical procedure?

**Comment by ekorchmar** [comment]
It looks like the concept 2002012 "Incision, excision, and occlusion of vessels" from ICD9Proc was wrongly built in between those concepts in SNOMED hierarchy. SNOMED itself does not consider it a surgical procedure, and it would be a stretch by most definitions to call it such. We'll look into it.

**Comment by clairblacketer** [comment]
Wonderful! Thank you for the quick response.

**Comment by cgreich** [comment]
> should venipuncture be considered a surgical procedure

It actually is, @clairblacketer. And theoretically we could write a record like that each time a Measurement is obtained in blood or other body fluid you need to prick the patient for. But since it is such a trivial "procedure" we don't record it. We should have a convention to not do that even when it is explicitly provided, unless Cost records are attached to it.

**Comment by TinyRickC137** [comment]
Can we close this issue? It has been here for a while
@cgreich @clairblacketer

**Comment by cgreich** [comment]
We should.
