### ISSUE TITLE
Lymphocytic Leukemia Incorrect Descendants

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#274]
It seems that the concept_id 440059 (recurrent disease) is listed as a SNOMED to MedDRA equivalent in the CONCEPT_RELATIONSHIP table to 6 different leukemia preferred terms. This causes 4282316 (recurrent major depression) to become a descendant of 35104382 (lymphocytic leukemia).

**Comment by p-talapova** [comment]
@clairblacketer technically, a relationship_id of "SNOMED - MedDRA eq" does not affect the OMOP hierarchy. @dimshitc please correct me if I am wrong. 
What is more interesting, "recurrent major depression" is not a descendant of "lymphocytic leukemia" and it had never been (as I see)
![image](https://user-images.githubusercontent.com/42737398/104136218-7c945980-539d-11eb-8ef0-d25bbe76e53f.png)

**Comment by dimshitc** [comment]
@p-talapova, unfortunately "recurrent major depression" is a descendant of "lymphocytic leukemia"
look:
```
select * from concept_ancestor an
join concept a on a.concept_id = an.ancestor_concept_id
join concept d on d.concept_id = an.descendant_concept_id
where a.concept_id =35104382 --lymphocytic leukemia
and d.concept_id =4282316 -- recurrent major depression
```
;
There's no direct relationship between these concepts, but the ancestry exists.
;
And the hierarchy is affected by this relationship, look at the reverse one
`select * from relationship where relationship_id='MedDRA - SNOMED eq';`
defines ancestry =1
;
It is in the plan for this year to fix the relationships between SNOMED and MedDRA, but it depends on the work done by MedDRA guys (they claimed to release some mappings between SNOMED and MedDRA in 2021).

**Comment by p-talapova** [comment]
@dimshitc thanks for clarifying this!

**Comment by Alexdavv** [comment]
A little bit more context:
https://forums.ohdsi.org/t/relation-between-meddra-and-snomed/6556

**Comment by MSalavei** [comment]
@mik-ohdsi Currently I don't see this problem. Currently we have only valid relationship 'maps to'  between  MedDRA concept_id 35809121 (Disease recurrence) and SNOMED concept_id 440059 (recurrent disease).

**Comment by mik-ohdsi** [comment]
@MSalavei  - great to hear that. If you can confirm that with the latest MedDRA fixes this issue is solved, Tag Clair as the original poster and close the issue with a comment.

**Comment by Alexdavv** [comment]
It's not actually solved... We've only removed a hierarchy between MedDRA and SNOMED completely, because:

- the links were not clean so the definition of this sort of relationship was blurred - they targeted mostly downhill (with the considerable jumps between the hierarchy levels), but also uphil or to the full equivalent concepts. While they always ened up with a record in the concept_anceptor table where MedDRA was on the top of SNOMED what wasn't really true.
- the links were ambigios 1-to-many;
- the links didn't provide a good coverage - only 39% of PTs were mapped. And even within the MedDRA term you could have some links, but also miss others.

Now we need to decide whether we want to recover this hierarchy and how.
Let's continue discussion [here](https://forums.ohdsi.org/t/relation-between-meddra-and-snomed/6556/19).
@cgreich @mik-ohdsi @MikitaSalavei

**Comment by MSalavei** [comment]
Hierarchy between MedDRA and SNOMED was created in February 2024 according to principles listed here: https://forums.ohdsi.org/t/meddra-overhaul-discussion/20896
