### ISSUE TITLE
Question about Meas Value and Qualified Value

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/Vocabulary-v5.0#297]
Can someone explain to me what the difference is between Meas Value and Qualified Value

![image](https://user-images.githubusercontent.com/7252105/80812850-0feb7d00-8bc9-11ea-94f4-42b990b9d116.png)

I see Qualifier Value in the Class column and then Observation as the domain and for others I see Answer as Calss and Domain Meas Value??

Why is once per month different from once per year? or why is there not a once a year Meas Value?

**Comment by cgreich** [comment]
Because those are just imported as is from SNOMED. "Qualifier Value" is a SNOMED attribute. Qualifier values form a hierarchy of numeric values. In that sense they are similar to our Measurement Values. But we usually don't conceptualize numeric, but mostly qualitative values (positive, absent, etc.)

So, once per year you should really represent as value_as_number=1 and unit_concept_id="per year".  We need to clean this up. Will add a backlog item.

**Comment by PRijnbeek** [comment]
Ok i see. I like the idea of using those attributes. Is this a best practice i could have known?

________________________________

**Comment by cgreich** [comment]
Probably burried in the documentation somewhere. Concept class = either made by source or our way to organize within vocabulary, domain = main organizing principle in OMOP and determinant which table the record goes.
