### ISSUE TITLE
Map two HCPCS codes to ingredients

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#306]
Please create a relationship for these two HCPCS codes: https://athena.ohdsi.org/search-terms/terms?vocabulary=HCPCS&page=1&pageSize=15&query=esketamine

so that they are associated with an RxNorm like 1366617 (esketamine metered dose nasal spray). What I would like to do is pick up the HCPCS codes when I look for all descendants of the esketamine ingredient.

**Comment by dimshitc** [comment]
Hi @clairblacketer !
We think of mapping these concepts to 
RxNorm 1366617 (esketamine metered dose nasal spray)
and 
9202 Outpatient Visit (because it also says about a Visit type).
Thus given HCPCS concepts become non-standard and will not be included in the hierarchy.
Will this work for you?

Another question: what domain should these concepts have (it is a Visit and a Drug in the same time)? what should we chose? @cgreich

**Comment by clairblacketer** [comment]
@dimshitc this sounds great, thank you!

**Comment by cgreich** [comment]
Right now, we ignore the Visit. Because we do so for all the other similar HCPCS codes. But can you put into the box a to-do to pull them all out? Should be a simple job.

**Comment by p-talapova** [comment]
Mappings were released:
https://athena.ohdsi.org/search-terms/terms/40217310
https://athena.ohdsi.org/search-terms/terms/40217102
