### ISSUE TITLE
Non standard Autoimmune chronic active hepatitis - should be mapped to - Autoimmune hepatitis

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/Vocabulary-v5.0#337]
Concept id 45467000 should be mapped to 200762

**Comment by Alexdavv** [comment]
Thanks, @gowthamrao!

It's strange, but target SNOMED concept [200762 'Chronic active hepatitis'](https://athena.ohdsi.org/search-terms/terms/4026125) has 'Autoimmune chronic active hepatitis' among the accepted SNOMED synonyms, but it's not reflected in SNOMED attributes/hierarchy though. In the literature, it isn't recognized as a full synonym, as well as Chronic autoimmune hepatitis is not a full equivalent.

> Concept id 45467000 should be mapped to 200762

Wouldn't be a best choice to add this mapping to the existing one?

**Comment by MariaRohozhkina** [comment]
Thank you for waiting. It has been fixed in [this release](https://github.com/OHDSI/Vocabulary-v5.0/releases/tag/v20230831_1693510428.000000). 
Now you can find improved mapping of this [concept](https://athena.ohdsi.org/search-terms/terms/45467000) in the Athena. It has both "Maps to" links to [Autoimmune hepatitis](https://athena.ohdsi.org/search-terms/terms/200762) as well as[ Chronic active hepatitis](https://athena.ohdsi.org/search-terms/terms/4026125).
