### ISSUE TITLE
Document Ontology Codes in Wrong Domain

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Vocabulary-v5.0#362]
I believe, the [hierarchy of codes](http://athena.ohdsi.org/search-terms/terms/36209248) from the LOINC clinical document ontology should be under the Note domain as opposed to the Measurement domain.

**Comment by Alexdavv** [comment]
Now it's in the Observation Domain. Would it be appropriate to assign these concepts to the Note Domain considering that there is no note_concept_id field and the only place you'd use it is the note_class_concept_id field?

**Comment by Alexdavv** [comment]
Related forum post:
https://forums.ohdsi.org/t/question-about-domain-id-for-note/12694

**Comment by cgreich** [comment]
Strange. I was under the impression that's where they were. Must have fallen out at some point. Yes, let's bring them back.

**Comment by AEW0330** [comment]
@cukarthik mentioned on the OHDSI NLP WG call today that lack of progress on resolving this issue is impeding work of general importance to the several sites (including ours) who are developing approaches to automated mapping of document types and related information. I'm posting her to advocate for prioritizing its resolution and, if any further discussion is needed, to get it on the next Vocab Subgroup's agenda.

**Comment by Alexdavv** [comment]
Hmm. we don't have the "Note" Domain yet at all...
So we'll create it, @cgreich ?


For the prioritization - LOINC is in the workshop at the moment. We'll bring it on with the next release in Oct-Nov. Does it work for you, @AEW0330 @cukarthik ?

**Comment by cgreich** [comment]
I think so.

**Comment by TinyRickC137** [comment]
Somewhere along the way (2023), they became Notes. I am closing this issue as completed.
