### ISSUE TITLE
Why does the mapping of ICD-10 C11.9 differs from other ENT malignancies?

### ISSUE THREAD

**Issue by awrosen** [OHDSI/Vocabulary-v5.0#376]
Dear Everyone,

The ICD-10 code C11.9 (Malignant neoplasm: Nasopharynx, unspecified) exists in Athena as a non-standard concept, the standard concepts it maps to is Malignant tumor of nasopharynx (ID 4095312). 
Other ENT malignancies generally map to a concept with 'primary malignant neoplasm of..', e.g. ICD-10 c10.9, c09.9.
There exists a concept called 'Primary malignant neoplasm of nasopharynx' (ID 36684473). Is there a reason this was not used for the mapping, since it appears this would present a more uniform mapping logic?

KR

Andreas Rosen

**Comment by divakhnenko** [comment]
Dear Andreas, thank you for your feedback. We appreciate your enthusiasm to make vocabularies better.
There is truly non-standard mapping logic in the example. According to ICD10 official [guideline](https://icd.who.int/browse10/2019/en#/II) and OMOP CDM principles,  ICD-10 C00-С96 'Malignant neoplasm ...'  concepts should be mapped to SNOMED 'Primary malignant neoplasm of ...'  unless the secondary malignant neoplasm is mentioned in ICD-10 concept. Consequently, the ICD-10 code C11.9 (Malignant neoplasm: Nasopharynx, unspecified) is not properly mapped. 
The reason for it is the fact that the necessary SNOMED concept 'Primary malignant neoplasm of nasopharynx' (ID 36684473)  was released on 31 Jan 2019 while ICD10 mapping was done far earlier.
We are working on the improvement of all vocabularies and this issue will be fixed in the scheduled release.
Kind regards

Daryna Ivakhnenko, medical terminologist

**Comment by awrosen** [comment]
Dear @divakhnenko , thanks for the reply.

Is it easing you guys workload in any way that these issues are being reported when they are encoutered them or is it a complete waste of time?

Kind regards

Andreas

**Comment by divakhnenko** [comment]
This is an integral part of our work - to improve the quality of the vocabularies. So, yes, users' feedback is easing our workload:)
 Thank you again for your help.

**Comment by mik-ohdsi** [comment]
@irinazherko  -  this concept still has a one to many mappings. Should we remove one of them?

**Comment by IrynaZherka** [comment]
@awrosen the issue was one more time addressed during the August 2024 release. 
C11.9 (Malignant neoplasm: Nasopharynx, unspecified) is now mapped to the standard Primary malignant neoplasm of nasopharynx (https://athena.ohdsi.org/search-terms/terms/36684473).

Thanks a lot for the contribution!
