### ISSUE TITLE
Type Concepts dropped from version 4 vocabulary release  v4.5 28-AUG-20

### ISSUE THREAD

**Issue by don-torok** [OHDSI/Vocabulary-v5.0#383]
We have v4 release 'OMOP Vocabulary v4.5 28-AUG-20'.  

From v4 release OMOP Vocabulary v4.5 16-JUL-20
select count(*) from vocabulary_4_5_jul_20.concept c where c.concept_class like '%Type';
-- 339 rows

From v4 release 'OMOP Vocabulary v4.5 28-AUG-20'
SELECT count(*) from  vocabulary_4_5_aug_20.concept
WHERE concept_id IN( select concept_id from vocabulary_4_5_jul_20.concept c where c.concept_class like '%Type');
-- 1 row

Concepts are not suppose to disappear.

**Comment by dimshitc** [comment]
Hi @don-torok 
There was a big change in Type concepts
https://forums.ohdsi.org/t/important-vocabulary-release-type-concept-and-condition-status/11760
instead of all these Condition, Meas, Observation etc. Types we have universal set for all domains.
So, all Type concepts become non-standard,
And we have a rule that the whole vocabulary gots into v4.concept when it has at least one concept having standard_concept IN ('C', 'S')

**Comment by don-torok** [comment]
I understand the change in Type concepts.  Do not understand why it is OK for concepts to disappear from V4 concept table.  Basic rule that concepts are not deleted.  Need to review rule for creating v4.concept.

**Comment by cgreich** [comment]
@don-torok: The only reason we haven't officially deprecated V4 is because V6 is still hanging. But otherwise - tell your customer to upgrade. Stop using Windows XP.

**Comment by mik-ohdsi** [comment]
Hi @don-torok - reviewing old not yet closed issues. I understand "Please note, vocabulary exists in v4.concept when it has at least one concept having standard_concept IN ('C', 'S')." sounds a bit harsh. But for Type Concepts specifically, do you still bother? And is there a chance for you to convince the customer to migrate to v5.4, given that v4 seems only to have minimal support by now?

**Comment by TinyRickC137** [comment]
Anything rather than Vocabulary version 5 is not supported. 
Please let me know if some concepts are still missing.
