### ISSUE TITLE
Please Add SNOMED Codes to CONCEPT and CONCEPT_RELATIONSHIP for New 2021 ICD-10 CM Codes

### ISSUE THREAD

**Issue by User11122233** [OHDSI/Vocabulary-v5.0#393]
Please Add SNOMED Codes to CONCEPT and CONCEPT_RELATIONSHIP for New 2021 ICD-10 CM Codes.

**Comment by mik-ohdsi** [comment]
ICD10-CM 2021 is valid starting Oct 1st 2020. Please find attached a list of added codes and a conversion table filtered to codes becoming valid in 2020 => [CMS](https://www.cms.gov/medicare/icd-10/2021-icd-10-cm)

[icd10cm_codes_addenda_2021.txt](https://github.com/OHDSI/Vocabulary-v5.0/files/5311825/icd10cm_codes_addenda_2021.txt)

[ICD_10_CM_Conversion_Table_FY21.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/5311822/ICD_10_CM_Conversion_Table_FY21.xlsx)

**Comment by p-talapova** [comment]
@User11122233 New ICD10CM codes and their mappings were added to the concept and concept_relationship tables. 

SELECT *
FROM concept
WHERE valid_start_date = '2021-01-01'
AND   vocabulary_id = 'ICD10CM';

SELECT c.concept_id AS icd_id,
       c.concept_code AS icd_code,
       c.concept_name AS icd_name,
       r.relationship_id,
       d.concept_id AS target_concept_id,
       d.concept_code AS target_concept_code,
       d.concept_name AS target_concept_name,
       d.vocabulary_id AS target_vocabulary_id,
       d.domain_id AS target_domain_id
FROM concept c
  JOIN concept_relationship r ON r.concept_id_1 = c.concept_id
  JOIN concept d ON d.concept_id = r.concept_id_2
WHERE c.valid_start_date = '2021-01-01'
AND   c.vocabulary_id = 'ICD10CM'
AND   d.standard_concept = 'S'
AND   r.relationship_id IN ('Maps to','Maps to value')
AND   r.invalid_reason IS NULL
ORDER BY icd_code,
         relationship_id;

Also, they are available for search in the Athena.

**Comment by User11122233** [comment]
Good morning and thank you for the update, when I went to check the file called ‘concept’ I don’t see a value of start date later than 2020 and also I’m not seeing a value of ‘ICD10CM’ in the vocabulary_id column, is it possible these are missing or the wrong file was posted?

**Comment by mik-ohdsi** [comment]
Hi @User11122233 
you commented:
"Good morning and thank you for the update, when I went to check the file called ‘concept’ I don’t see a value of start date later than 2020 and also I’m not seeing a value of ‘ICD10CM’ in the vocabulary_id column, is it possible these are missing or the wrong file was posted? "
I am confused: where would you see such a file posted? You would have to download the latest vocabularies from Athena and ideally import them to your OMOP CDM.

Then you can carry out the above SELECT to find all entries that are new. 

To be honest, the start date should maybe have been in October 2020, as they are valid since then.
Let me consult @p-talapova on this topic.

Cheers - Mik
