### ISSUE TITLE
We need a standard visit concept for death

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Vocabulary-v5.0#398]
In the field VISIT_OCCURRENCE.discharge_to_concept_id we decided that it must contain a standard concept in the visit domain. However, in the case that the patient dies in hospital the discharge should be "expired" but there is no standard visit concept representing that idea.

I found this one in UBO4: https://athena.ohdsi.org/search-terms/terms/32218

Can we make it standard?

**Comment by Alexdavv** [comment]
Hii @clairblacketer 

The current convention has a couple of exceptions where you can go for another Domain. But death is not the case anymore since it lives in the person.death_datetime field.

`The discharge disposition (discharge_to_concept_id) should be filled with Visit concept. Death is no longer captured here. In addition to the Standard Visit Concepts the special concept 44814693 "Absent without leave" and 4021968 "Patient self-discharge against medical advice" can be used.`

But if you're on 5.3.1. I'm not really sure whether the 'Patient died' 4216643 concept is still a valid choice. What makes me doubt is the fact that this convention was introduced even sometime after the 6.0 release.

**Comment by cgreich** [comment]
Well, we should take this on as one of the future debates in the CDM WG club. Took as a long time to get to the point that we disentangled place of service, specialty, care site, and - relevant to this - setting of the patient in relation of the healthcare services. And not the other way around. The OMOP CDM is all patient centric. If the data are the other way around we need to pivot it back and make it consistent. 

Unless there is a use case to the opposite. Let's go through them.

**Comment by TinyRickC137** [comment]
@cgreich @clairblacketer 
Any news on the debate? Do you still think it may be needed?

**Comment by cgreich** [comment]
Don't think it is needed. The patient got discharged, and at that day a DEATH record is written. I don't think it was the intention of the institution to "discharge to death". That would be called "manslaughter" or "murder". We don't have the right data model for those.

**Comment by MelaniePhilofsky** [comment]
Agree with @cgreich 

Also, we only "admit from" or "discharge to" another healthcare institution. We don't have standard concepts for home, prison, etc.
