### ISSUE TITLE
Oxygen in RxNorm Extension a mess

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Vocabulary-v5.0#419]
Please add QA rules against things like:

40737135 Oxygen 2600000 ML
40737101 Oxygen 2600000000 MG
5856409 oxygen 3 MG
5856422 oxygen Injectable Solution (almost as good as Trump's injection of bleach or light into the blood stream)
35856418 oxygen Oral Tablet
44104433 Oxygen 0.099 % and 44091401 Oxygen 0.0992 % (don't we have a 90% or 95% corridor?)

**Comment by p-talapova** [comment]
Thanks for the finding. The problem is coming from the NCCD vocabulary and starts from the Chinese name of 氧 注射剂 and its machine translation. We assign dose forms as attributes of Drug Products using word patterns, and this process is automated. Thus erroneous translation (like in this case) gives us the assignment of an erroneous attribute and leads to the creation of new RxE entities. A great reason to extend our QA methods to prevent such surprises.

**Comment by mik-ohdsi** [comment]
Hi @cgreich , 
the first two are actually remotely okay. That is, if we want to record a 260 litre liquid oxygen tank by Linde Gas in OMOP. The others definitely need a caring hand. The last one seems to be suffering from some conversion error (why would you use 0.099% oxygen?) while the original drug seems to be 99% oxygen.
We are on it! ~Mik

**Comment by divakhnenko** [comment]
Hello @cgreich ,


We examined the NCCD source and found 28 strange concepts which have a link to Oxygen as an ingredient as well as a suspicious dose form (I add a list of them to this message : [nccd_oxygen.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/5702437/nccd_oxygen.xlsx) ). We are going to delete them for now from NCCD and RxNorm Extension.
However, I checked if Oxygen injection can be a treatment and it seems that yes (definitely only for alternative medicine https://en.wikipedia.org/wiki/Ozone_therapy) We have already faced with a lot of Chinese herbs in this source. So, Oxygen tablets, capsules or injections can be just another form of treating patients in eastern medicine. We should keep it in mind for future updates.
