### ISSUE TITLE
What happened to buformin?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/Vocabulary-v5.0#45]
Buformin is a first-line oral antidiabetic that is related to metformin, and is used more often than metformin in Japan. It is in RxNorm (1803) as well as ATC (A10BA03). 

In Vocab V4 it was in ATC, but not in RxNorm. In Vocab V5 it is completely missing.

**Comment by cgreich** [comment]
@schuemie:

It is still in ATC:
select * from concept where concept_code='A10BA03';

It is still not in RxNorm. Neither:
select * from concept where concept_code='1803'; -- at least no RxNorm pops up.
select * from rxnconso where rxcui='1803';

And it shouldn't, since the dope is not pushed in the United States. However, what we didn't do is to promote this to a standard concept. This will be in the fix with Gemscript/DM+D, we will have to do a lot of surgery there. So, couple weeks.

**Comment by schuemie** [comment]
Just for my understanding: drugs in RxNorm that are not used in the US are deleted from the vocab? Can you remind me why?

**Comment by cgreich** [comment]
They are not in RxNorm. RxNorm only has US drugs. And they are not deleted, they are just not standard concepts. Will all be fixed in the next release. We are working on the mixed vocabularies that allow queries to work in exactly the same way for non-US drugs as in RxNorm.

BTW: Did you want to give me the Korean drug source, so we can plug it in?

**Comment by vojtechhuser** [comment]
The term is found via the API
https://rxnav.nlm.nih.gov/REST/approximateTerm?term=buformin


The status of the term is however Alien
https://rxnav.nlm.nih.gov/REST/rxcui/1803/status



![image](https://cloud.githubusercontent.com/assets/7526119/16013615/292c6b60-315c-11e6-8f36-b4a996f12ff9.png)

**Comment by cgreich** [comment]
@vojtechhuser:

It's just an import from ATC. ATC 5th level, however, is not a good substitute for ingredients, because there are duplicates and there are combinations. So, we don't use them.

However, in the upcoming release we will have all these guys in as RxNorm Extension. Please stand by.

**Comment by aostropolets** [comment]
@schuemie @vojtechhuser 
Yep, RxNorm Extension has it, concept_id = 40798673
