### ISSUE TITLE
Remapping of deprecated codes

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Vocabulary-v5.0#489]
How do we handle deprecated codes? I was under the impression there are relationships to point us to a new code to use instead. For example, [40780291](https://athena.ohdsi.org/search-terms/terms/40780291) is a LOINC Hierarchy code that is deprecated. Sometimes organizations are mapping to classification codes b/c they do not know what the granular code should be based on their data. @cgreich and @mik-ohdsi interested to get your input.

**Comment by mik-ohdsi** [comment]
Hi @cukarthik , yes, it should have a "replaced by" relationship if, in the process of updating the vocabulary, we actually have knowledge about a proper replacement. If a code ceases to be valid because the source simply doesn't have it anymore and it is not "replaced", it will become orphaned like this one. I briefly searched LOINC and did not find a proper replacement for this hierarchy component for Total Cholesterol in Serum, Plasma or Blood... Do you know one?

**Comment by p-talapova** [comment]
Hi @cukarthik, LOINC does not support the replacement of LOINC Hierarchy concepts. Therefore, the vocabulary team has to build the replacement relationships manually that is time-consuming and rarely applicable to Classification concepts.
But theoretically, this is possible.

However, in order to obtain all related LOINC descendants, I would propose using the following codes:
1. A valid Classification LOINC Hierarchy concept with a specified specimen source: [37027885	Cholesterol | Serum or Plasma | Chemistry - non-challenge](https://athena.ohdsi.org/search-terms/terms/37027885).
2. A Standard SNOMED concept with an unspecified specimen source: [4299360 Cholesterol measurement](https://athena.ohdsi.org/search-terms/terms/4299360) (contains LOINC codes as children as well).

**Comment by cukarthik** [comment]
Thanks!
