### ISSUE TITLE
LOINC Linguistic Variants

### ISSUE THREAD

**Issue by mgraauw** [OHDSI/Vocabulary-v5.0#506]
The LOINC Linguistic Variants (containing translations) aren't listed in the files to be downloaded - any plans to support those?

**Comment by Alexdavv** [comment]
What files are you referring to? If LOINC sources - then it's provided by [LOINC](https://loinc.org/downloads/accessory-files/).
If you're talking about OMOP vocabularies, we don't distribute the content using additional files. Everything is in the standardized vocabulary tables, and linguistic variants are in the concept_synonym table. Are you interested to have them for LOINC?

**Comment by mgraauw** [comment]
LOINC publishes the translations (Dutch is what I'm interested in) in Linguistic Variants in https://loinc.org/downloads/accessory-files/.
Here: https://github.com/OHDSI/Vocabulary-v5.0/tree/master/LOINC are the files OHDSI vocab uses: no Linguistic Variants 
From this: https://ohdsi.github.io/TheBookOfOhdsi/StandardizedVocabularies.html
" Non-English names are recorded in CONCEPT_SYNONYM as well, with the appropriate language concept ID in the LANGUAGE_CONCEPT_ID field. "
I conclude that the OHDSI does support multilingual concept, i.e. Dutch and other translations for concepts. Apparently the OHDSI vocab does not use those for LOINC.
Indeed, https://athena.ohdsi.org/search-terms/terms/37045866 does not mention any translation of 'Salix caprea', whereas https://loinc.org/LP13974-8/ mentions our 'boswilg'.
So I don't need the files - I've got similar software importing LOINC and Snomed (with Dutch translations), I am consider using the software provided by OHDSI instead, but w/o translations it would not suit my use case.

**Comment by Alexdavv** [comment]
The only language we added for LOINC is Chinese: here is the [script](https://github.com/OHDSI/Vocabulary-v5.0/blob/c8db21eaff82f705354f666e31917cd512d8492d/LOINC/load_stage.sql#L1831).
In order to avoid importing any additional tables, we used the translations provided by [UMLS](https://www.nlm.nih.gov/research/umls/sourcereleasedocs/index.html).


> Indeed, https://athena.ohdsi.org/search-terms/terms/37045866 does not mention any translation of 'Salix caprea'

I see. It looks like UMLS doesn't give us linguistic variants for LOINC parts (Components, Method, etc.).


> whereas https://loinc.org/LP13974-8/ mentions our 'boswilg'.

Can you check is it also provided in the LOINC Linguistic Variants file?

Additional languages can be added, but it would be good to improve the Athena UI/sorting first: https://github.com/OHDSI/Athena/issues/254

**Comment by mgraauw** [comment]
It is in LOINC, I use those files regularly. Anyway, the question was more if this was planned or scheduled. If it is not, don't do it on my behalf, it's not that urgent. Thanks for your responses
