### ISSUE TITLE
Outdated ATC version

### ISSUE THREAD

**Issue by marcel1334** [OHDSI/Vocabulary-v5.0#541]
The current version of the ATC is of May 2020. There are many new ATC codes since 2021 and also other changes.

Basically every new year there are updates to ATC. Can ATC be updated yearly at the beginning of the year? Often these new codes are announced far ahead.

Especially in Europe, the ATC code is used a lot. Having up to date ATC codes is important.

**Comment by mik-ohdsi** [comment]
Hi @marcel1334  - a new version is in the works. We had some difficulties as it was not only a refresh with the 2021 version but we also had to figure out and fix a couple of shortcomings in the generation and release process. But... we also included the changes for 2022 already. Expect this release to be there in a couple of days (or less).

**Comment by marcel1334** [comment]
Super, thanks for fast response. Does it also include the extra standard ingredients for all these new ATC codes?

**Comment by mik-ohdsi** [comment]
Hi @marcel1334  - the ATC refresh is in the latest release. We still have a great number of ATC codes that are not mapped to ingredients because they do not exist. We have not yet used ATC to create RxNorm Extension entries. Please review the current ATC. @p-talapova has tried to accomodate as much of your input as possible and has fixed a number of things in the process.
