### ISSUE TITLE
HCPC-->RxNorm Injectable Mapping

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#55]
Checked in VERSION v5.0 3-Apr-2015

Some of these drugs don't get to a clinical drug.  I would expect proposals like this to make sense.

**Example 1**
HCPC - `J2426-Injection, paliperidone palmitate extended release, 1 mg`
CURRENT MAP - `703244 - paliperidone`
PROPOSED ADDITION - `40166614-paliperidone Injectable Suspension `

**Example 2**
HCPC - `J2794-Injection, risperidone, long acting, 0.5 mg`
CURRENT MAP - `735979-Risperidone`
PROPOSED ADDITION - `40080292-Risperidone Injectable Suspension`

**Comment by cgreich** [comment]
Not quite. 40166614 "Paliperidone Injectable Suspension" is a Clinical Drug Form.containing "Paliperidone". But there is another Drug Forms for injectables: 40165674 "Paliperidone Prefilled Syringe". You can't map to one and not to the other, and you can't map to both, because that would be an AND between these two drugs, (meaning, the patient got both the syringe and hte injectable solution). So, the existing mapping is correct.

**Comment by pbr6cornell** [comment]
Why can't a source code map to a clinical drug form, now that they are
standard?  why can't we select one as a primary mapping?

**Comment by cgreich** [comment]
Hey!! This was closed already! :)

The rule is to map to the most precise possible RxNorm Concept:

Branded Drug or Clinical Drug
Branded Drug Form or Component
Clinical Drug Form or Component
Ingredient.

the first 4 need to be unambiguous, i.e. only if there is a single Concept of a concept_class_id we map. If not, we try the next. For the ingredients, they can be multiple. That's the default. We don't go higher to drug classes, becasue they are not unique.

**Comment by pbr6cornell** [comment]
Using the lgoic you've provided, shouldn't the source code:

HCPC - J2426-Injection, paliperidone palmitate extended release, 1 mg

get mapped to the RxNorm Clinical Drug Form concept of:

40166614 - paliperidone Injectable Suspension


Similarly for the other example, source code:

HCPC - J2794-Injection, risperidone, long acting, 0.5 mg
would map to:
40080292-Risperidone Injectable Suspension


The source code is unambigious in its formulation.  We are not able to map to a Branded Drug or Clinical Drug concept, but we can select a Clinical Drug Form component, rather than rolling all the way up to the ingredient concept.

These two specific examples are pertinent to our team, since there is a lot of ongoing research examining the differential effects of oral vs. injectable antipsychotics.  But the general issue here is broader:  we'd like to preserve as much information from the source as possible, and keeping the clinical drug form concept, which rolls up to ingredient, gives us additional opportunities to support our analytical use case that an ingredient-mapping alone does not.

**Comment by cgreich** [comment]
@pbr6cornell:

Almost. For paliperidone it won't work, because there is the injectable suspension, but also the prefilled syringe, unfortunately. Either one could be used in J2426.

For Risperidone you are right. It needs fixing.

We just did exactly this job for CPT4. All of them are mapped to the lowest possible RxNorm that's still unambiguous. Will review this for HCPCS as well. I'll also bring it up with Olivier. I am sure he has already thought about it.

**Comment by pbr6cornell** [comment]
The injectable suspension vs. prefilled syringe is a RxNorm messiness.  Can't we select one as a convention, if there is no information otherwise?  To meet our analytical use case, we have to be able to separate out forms, because the drugs are fundamentally different, so a mapping only to the ingredient level will not work.

**Comment by cgreich** [comment]
I hear you, and I know why you would want it. But there are three forms for parenteral administration of drug: "Injectable Solution", "injectable Suspension" and "Prefilled Syringe" (which can contain either a solution or a suspension). If we abolish the syringe we would need:

  - Remap all mappings from the sources to the injectable solution or injectable suspension, and we wouldn't know to which one.
  - Reorganize and rename all Drug Products, Drug Components and Drug Forms, including all the relationships between them.

That would be a monster surgery and a drastic departure from RxNorm. You really want to do that?

I really don't have a good idea, but maybe this one: We could introduce a new relationship to a route of administration "Parenteral" and give that to all concepts that have one of the three Drug Forms, including the Source Concepts So, you could then use the ingredient from the drug_concept_id, and the route from the drug_source_concept_id.

**Comment by pbr6cornell** [comment]
If we were to just treat this J code as a 'source code', (meaning solve it
as a custom oneoff, not trying to provide a generic solution) then I would
just arbitrarily choose to map to one of the three 'candidate' clinical
drug form concepts.  I don't think we want to do massive surgery on the
vocab and certainly don't want to be reorganizing rxnorm.  But we will need
an approach for manually 'overriding' the general vocab when we find these
types of mappings that don't meet our needs.

**Comment by cgreich** [comment]
Hm. We should think of how to formalize it. Right now, we have a mapping that tries to be contradiction-free, driven by the general anxiety of "loss" during the mapping. We could change that to make it a more pragmatic mapping. Or create a solution of alternative mappings. Not sure how we would that transparent. CDM 6.0.

**Comment by ericaVoss** [comment]
This mapping is looking good to me now for my two examples (HCPC --> Clinical Drug).  Don't know if you manually fixed or the drug overhaul fixed it.  Should I close?

**Example 1**
HCPC - `J2426-Injection, paliperidone palmitate extended release, 1 mg`
OLD MAP - `703244 - paliperidone`
CURRENT MAP - `40165674-paliperidone Prefilled Syringe`

**Example 2**
HCPC - `J2794-Injection, risperidone, long acting, 0.5 mg`
OLD MAP - `735979-Risperidone`
CURRENT MAP - `40080292-Risperidone Injectable Suspension`

**Comment by cgreich** [comment]
We automated it. We have a script to map any drug list. Will use it on NDC.
