### ISSUE TITLE
No CPT Concepts in V5.0 06-DEC-21

### ISSUE THREAD

**Issue by mpatel-cai** [OHDSI/Vocabulary-v5.0#572]
I reconstituted the CPT4 concepts using the shell script provided, but the CONCEPT table ends up with 0 CPT4 concepts.

**Comment by don-torok** [comment]
The CPT4 java script creates a log file.  Can you post that?

**Comment by mpatel-cai** [comment]
[logfile.log](https://github.com/OHDSI/Vocabulary-v5.0/files/7694761/logfile.log)

**Comment by don-torok** [comment]
The log report indicates the concept table has been updated with CPT4 concepts.  How did you determine that there are 0 CPT4 concepts?

Note we should move this discussion to the Vocabulary Forum https://forums.ohdsi.org/c/vocabulary-users since, at least for now, I do not think we are discussing a coding error.

**Comment by mpatel-cai** [comment]
@don-torok 
Sorry, I realize I wasn't clear with how I discovered this. 

After copying CONCEPT.csv into the CONCEPT table, I check the counts by performing a GROUP BY on vocabulary_id.

**Comment by mpatel-cai** [comment]
@don-torok 
Double checked right now and I believe it must been an error in the way I had reconstituted the CPT4 concepts. They are now in the CONCEPT table. Thanks for your feedback!
