### ISSUE TITLE
Obsolete RxNorms are appearing as valid active RX codes in Athena

### ISSUE THREAD

**Issue by sdard** [OHDSI/Vocabulary-v5.0#606]
Ex 1: in Athena this RxNorm is listed as active: https://athena.ohdsi.org/search-terms/terms/40232708 . However, according to this, it's been inactive for more than 8 years https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=328468.

Ex 2: in Athena this RxNorm is listed as active: https://athena.ohdsi.org/search-terms/terms/40232701 . However, according to this, it's also been inactive for more than 8 years https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=328468

**Comment by cgreich** [comment]
@sdard:

The RxNav link you posted is nitroglycerin, you probably meant https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=1049685 and https://mor.nlm.nih.gov/RxNav/search?searchBy=RXCUI&searchTerm=1049606. 

But you are right, they are not active in RxNav. Why? They are not on the market in the US. Dazidox apparently is completely gone as a brand, and Roxicodone only exists as 5, 15 and 30 mg tablets, not as a solution.

RxNav and OMOP have different criteria for validity. OMOP does not invalidate drug concepts merely because they are off the markets. It would kill all the old data when they still were. Only if the composition of the concept (ingredients, dose form, strength, brand name) was wrong and needs to be corrected concepts are invalidated. For example, originally oxycodone as an ingredient was simply given as "oxycodone", rather than "oxycodone hydrochloride". See as an example the [old](https://athena.ohdsi.org/search-terms/terms/19071716) and [current](https://athena.ohdsi.org/search-terms/terms/40232720) 15 mg Roxicodone tablets.

**Comment by sdard** [comment]
@cgreich thank you!
