### ISSUE TITLE
OHDSI CMS POS Crosswalk: visit_detail_source_value = 10 | 58

### ISSUE THREAD

**Issue by krevett-iqvia** [OHDSI/Vocabulary-v5.0#626]
	Observation (April ETL): The counts for visit_detail_source_value = 10, visit_detail_type_concept_id = 32871 increased from 432 counts to 143,724, but do not have a source_concept_id on ATHENA yet. Similar, visit_detail_source_value = 58 has a missing source_concept_ID. Both of these appear to be eligible place of service codes. 

In short, we request that place of service codes be implemented for visit_detail_source_value  values of 10 and 58.  We do not have a source_concept_id on ATHENA - and these appear to be valid place of service codes.

**Comment by mik-ohdsi** [comment]
Hi there!
this is somewhat related to #379 - only we are a little stuck here because code re-use has not yet been addressed. It is really not easy to solve, as it breaks an existing convention and we haven't been able to get buy-in from the community... @cgreich - I would like to push this again in the Vocabulary WG

**Comment by mik-ohdsi** [comment]
@krevett-iqvia - will be pushing this after the summer break, with POS becoming a guinea pig for solving the "code re-use" problem.

**Comment by krevett-iqvia** [comment]
Thank you for this update.  Should I assume this issue will be addressed for the next vocab release - expected date being: 08222022?

**Comment by mik-ohdsi** [comment]
Hi @krevett-iqvia , 
the next release is mostly about SNOMED (and has required most of our resources) and it require a couple more days as we found a couple of issues that need fixing in the final checks. The summer release I was referring to was meant to come a little later, maybe it would rather make sense to call it the Indian Summer release..,

**Comment by krevett-iqvia** [comment]
Thanks for the update @mik-ohdsi.  When do you expect, roughly, the Indian summer release to happen?

**Comment by revettk** [comment]
Hi Michael, has there been any progress made on this issue?  We are still seeing about 20% variation in our data - increases month-to-month since around Sept.  The numbers dropped from August - which was 120% increase month/month for:
visit_detail_concept_id 0   -> POS system - visit_detail_source_value == 10|58.  I know there was a s/w re-use issue involved in this - not a straight forward task.  Thank you for looking at this.

**Comment by krevett-iqvia** [comment]
@mik-ohdsi I believe I have not heard of any failures based on this ticket.  I apologize for the delay in providing feedback - this ticket can certainly be closed.  Thank you very much!!!!!!
