### ISSUE TITLE
Wrong mapping for all ICD10 variants A

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Vocabulary-v5.0#637]
ICD-10 [Salmonella enteritis](https://athena.ohdsi.org/search-terms/terms/45542510) and all other sister ICD-10s of the same concept_code should be remapped from [Arizona infection](https://athena.ohdsi.org/search-terms/terms/4288241) to [Salmonella gastroenteritis](https://athena.ohdsi.org/search-terms/terms/196328).

**Comment by Tru-Tran** [comment]
Agreed.  Here are some other ones to consider (OMOP: ICD10-SNOMED maps):

OMOP Maps:
35210698 - Microcephaly (ICD10CM)
---> 381114 - Microcephalus (SNOMED) - No longer active but still in Athena
Existing SNOMED:
	1148757008 (Does not exist in OMOP) - Microcephaly (finding)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
45547730 - Dementia with Lewy bodies (ICD10CM)
---> 380701 - Diffuse Lewy body disease (SNOMED)
Existing SNOMED:
312991009 (OMOP 4196433) - Senile dementia of the Lewy body type (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
18669 - Toxic effect of trichloroethylene, undetermined (ICD10CM)
---> 4010682 - Tetrachloroethylene poisoning (SNOMED)
Existing SNOMED:
	290520009 (OMOP 4157800) - Trichloroethylene poisoning (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
1568808 - Vitreomacular adhesion (ICD10CM)
45567068 - Vitreomacular adhesion, bilateral (ICD10CM)
45571987 - Vitreomacular adhesion, unspecified eye (ICD10CM)
45586473 - Vitreomacular adhesion, right eye (ICD10CM)
45605694 - Vitreomacular adhesion, left eye (ICD10CM)
---> 4035449 - Vitreo-retinal adhesion (SNOMED)
Existing SNOMED (more discrete):
	1119266006 (Does not exist in OMOP) - Vitreomacular adhesion (disorder)
        10762111000119102 (OMOP 36712704) - Vitreomacular adhesion of bilateral eyes (disorder)
        10762151000119101 (OMOP 36712705) - Vitreomacular adhesion of left eye (disorder)
        10762191000119106 (OMOP 36712706) - Vitreomacular adhesion of right eye (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
35206702 - Dietary folate deficiency anemia (ICD10CM)
---> 4021911 - Megaloblastic anemia due to poor nutrition (SNOMED)
Existing SNOMED:
	267518003 (OMOP 4143351) - Folate deficiency anemia due to dietary causes (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
45592098 - Juvenile osteochondrosis of head of femur [Legg-Calve-Perthes], left leg (ICD10CM)
---> 4006963 - Avascular necrosis of the capital femoral epiphysis (SNOMED)
Existing SNOMED:
	355208009 (OMOP 4230824) - Juvenile osteochondrosis of lower extremity (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
1572274 - Abnormal glucose (ICD10CM)
---> 4042728 - Blood glucose abnormal (SNOMED)
Existing SNOMED:
	102660008 (OMOP 438557) - Abnormal glucose level (finding)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
10964 - Strain of muscle, fascia and tendon at neck level (ICD10CM)
---> 4022201 - Injury of musculoskeletal system (SNOMED)
Existing SNOMED:
	360450007 (OMOP 4235779) - Strain of neck muscle (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
1572439 - Avulsion and traumatic amputation of part of head (ICD10CM)
---> 375415 - Injury of head (SNOMED)
Existing SNOMED:
	284554003 (OMOP 4113009) - Avulsion - injury (disorder)
	722635008 (OMOP 36716584) - Traumatic amputation of part of head (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
45586320 - Hydrocephalus in diseases classified elsewhere (ICD10CM)
---> 375239 - Degenerative brain disorder (SNOMED)
Existing SNOMED:
	230745008 (OMOP 4043738) - Hydrocephalus (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
35208271 - Toxic gastroenteritis and colitis (ICD10CM)
---> 4043371 - Inflammatory disorder of digestive tract (SNOMED)
Existing SNOMED:
	71583005 (OMOP 197596) - Toxic gastroenteritis (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
1576134 - Occupational exposure to risk factors (ICD10CM)
---> 4059637 - Work environment deleterious (SNOMED)
Existing SNOMED:
	16090731000119102 (OMOP 42535212) - Occupational exposure to risk factor (event)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
37200010 - Castleman disease (ICD10CM)
---> 4118225 - Angiofollicular lymph node hyperplasia (SNOMED)
Existing SNOMED:
	207036003 (OMOP  4118225) - Castleman's disease (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps (OMOP relationship does not make sense):
37201089 - Need to immediately re-void (ICD10CM)
---> 4086444 - Patient registration status (SNOMED) - ?????
Existing SNOMED:
	249289004 (OMOP 4091219) - Must urinate repeatedly to empty bladder
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
35210458 - Epicranial subaponeurotic hemorrhage due to birth injury (ICD10CM)
---> 439130 - Subgaleal hemorrhage (SNOMED)
Existing SNOMED:
	762286005 (OMOP 42538556) - Subgaleal epicranial subaponeurotic hemorrhage due to birth injury (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
1568039 - Disorders of peroxisome biogenesis (ICD10CM)
---> 441268 - Disorder of peroxisomal function (SNOMED)
Existing SNOMED:
	742876007 (OMOP  42538228) - Peroxisome biogenesis disorder (disorder)
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
45581175 - Meningitis in Chagas' disease (ICD10CM)
---> 442278 - Trypanosomiasis with meningitis (SNOMED)
Existing SNOMED:
	1089781000119109 (OMOP 46269916) - Meningitis due to Chagas disease (disorder) 
---------------------------------------------------------------------------------------------------------------------
OMOP Maps:
45564481 - Laceration of blood vessel of other finger, initial encounter (ICD10CM)
---> 443419 - Laceration - injury (SNOMED)
---> 194209 - Digital blood vessel injury
Existing SNOMED:
	735834009 (OMOP 42536827) - Laceration of blood vessel of finger (disorder)

**Comment by irinazherko** [comment]
The changes were implemented during the latest release
