### ISSUE TITLE
ICD10CM R92.2 Mapping

### ISSUE THREAD

**Issue by Piper-Ranallo** [OHDSI/Vocabulary-v5.0#649]
ICD10CM code R92.2 is used to document an inconclusive finding on a mammogram.

it is currently mapped to the following standard concept in OMOP:
concept_id 4324693: SNOMED SCTID 71651007 | Mammography (procedure) |

I believe we want it mapped to:
concept_id 37108814: SNOMED SCTID 134301000119104 | Inconclusive mammography finding (finding) |

Here is a description of the code:
![image](https://user-images.githubusercontent.com/44986641/177866749-25439475-aabd-40b1-9f50-33ca5220fff5.png)

**Comment by Piper-Ranallo** [comment]
Hmm... I see what you're saying, Christian. An inconclusive mammogram is really the result (inconclusive) of a test (mammogram). 

Yet, the code itself doesn't really represent the  mammogram either.  it represesents a clinical finding. It looks like it's often used to indicate that the patient has dense breast tissue (thus making traditional mammography less likely to detect a mass). We have a corresponding procedure code in our data that represents the mammogram (procedure). Is there any reason not to map it to the concept that precisely represents the meaning of the code?  

Piper

**Comment by mik-ohdsi** [comment]
seems like @Piper-Ranallo wasn't yet satisfied with what you said, @cgreich. Try again?

**Comment by cgreich** [comment]
Trying again. :)

> Is there any reason not to map it to the concept that precisely represents the meaning of the code

If there is no meaning for which you would be able to define a use case. Right now, the concept says:

1. There was a mammography (should be recorded as such in PROCEDURE_OCCURRENCE.
2. The breast has high density tissue (might be recorded as an OBSERVATION,
3. The mammography did not lead to a diagnosis of anything (we have that by not writing a CONDITION_OCCURRENCE record)

Works? 

The connection between them, in that there was no diagnosis because the tissue is dense, is not data. That is medical text book. We don't need to repeat that here. And we should most certainly not do that for negative results. Could be anything why a diagnosis wasn't achieved: The report got lost, the patient checked herself out, the physician rolled her eyes because of the incompetent sonographer, whatever.  We don't care.

**Comment by Piper-Ranallo** [comment]
Thanks @cgreich  and @mik-ohdsi.

The bottom line is this: The meaning of this code is not just "inconsclusive mammogram", it is "(mammogram) image shows no evidence of abnormal breast tissue (potential lesion) however, because the tissue visualized is dense, the mammogram is interpreted as being  "inconclusive" rahter than "negative". In other words, a radiologist seeing an absense of any abnormal tissue will interpret the mammogram as "negative" in a woman who does not have dense breast tissue, but as "inconclusive" in a woman who does have dense breast tissue. 

The confusion I think is that the name associated with the code (inconclusive mammogram) does not represent the true clinical meaning of the code **_as it is used in routine clinical practice._**. I spoke with our coders and my understanding is that this code is often used as a "diagnostic code" justifying more expensive immagining modalities. 

The use case is this: The finding of 'dense breasts' is an important variable required in any research related to breast cancer detection and detection methods. 

Piper

**Comment by cgreich** [comment]
Hi @Piper-Ranallo:

Hm. The code says, as you summarized, that the mammogram is inconclusive.

1. We record that there was a mammogram.
2. We record an observation "dense breast tissue". 
3. We do not record any diagnosis, because none could be made

Now, what information is missing or wrong? A justification for payment or for the need for further diagnostic workup is **not** a diagnostic code. It is just that, a justification, which is irrelevant to OMOP, as it is not for analytics of claim rules. There are quite a few of those pseudo-diagnoses in ICD10, and they are all mapped to some other domain. Had the mammogram found something the diagnosis would be "Breast cancer" maybe with the condition status "Preliminary diagnosis". But that cannot be made.

I know that you want your code the way it is, but that violates the structure of the CDM and Vocabularies. 

Help me here. :)

**Comment by Piper-Ranallo** [comment]
Ah... 
so this code does also map to a concept for "dense breast tissue" (in domain observation)?
I may need to load the newest vocabulary files to see this mapping, I am still seeing only the mapping to the procedure (mammogram).

Piper

**Comment by mik-ohdsi** [comment]
@Piper-Ranallo - we came to the conclusion that we are not changing the mapping, right?

**Comment by Piper-Ranallo** [comment]
Hi @mik-ohdsi 
Ok to close. I will re-open if needed.
This fell off my radar.

Piper
