### ISSUE TITLE
Observations or Conditions

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Vocabulary-v5.0#663]
I was using ARES today to look at top CONDITION_OCCURRENCE records in one of my database and found these were the top 3:

![image](https://user-images.githubusercontent.com/6305439/184226501-373deab9-bef7-4d4d-b6cc-7ea9b0e63f53.png)

I double checked ATHENA and see the top code is  in fact a Condition per the OMOP Vocabulary.

I would have assumed these were OBSERVATIONS.  Is the domain of Condition correct?  If it is, could you help me understand?

**Comment by ekorchmar** [comment]
Most likely a recent developing. It's a common bug that returns in one form or another every SNOMED release. SNOMED hierarchy for test results is a little bit weird with multiple parents from different branches, and it affects which parent is chosen during the domain assignment.

**Comment by cgreich** [comment]
You are right, @ericaVoss. This is a known problem. Misclassification of domain due to the SNOMED hierarchy. We are planning on a full refactoring, including de-standardization of duplicate concepts.

**Comment by dimshitc** [comment]
@Alexdavv can you include this fix in the upcoming SNOMED refresh?

**Comment by cgreich** [comment]
@Alexdavv: Sounds like you need to add another "peak" for Observations: 4041436.

**Comment by Alexdavv** [comment]
This is to some extend by the design... The plan was to move these pre-coordinated tests to the Measurement Domain. We even [tried it but revoked](https://github.com/OHDSI/Vocabulary-v5.0/blob/6500f8f98f125bdeb4c8765f835701367b99f665/SNOMED/load_stage.sql#L1655). And the reason was that we haven't finally agreed to allow the Measurements to be the pre-coordinated entities. That's why they have to be split beforehand.

> can you include this fix in the upcoming SNOMED refresh? I mean the domain change

> Sounds like you need to add another "peak" for Observations: 4041436

Most of the things like that are in the Condition Domain for the years, and there's a reason for that: majority of the labs tests with the result are the halfway Conditions and much closer to it than to the Observation. Also it prevents users from adding another value to the concept that already has a value (value_as_concept_id is not allowed in the condition_occurence table). Let's not again crate the temporal changes that can confuse people even more...

Any the release is on it's way to prod anyway.

**Comment by cgreich** [comment]
True. We would need to split. You are right. 

Don't understand the "halfway Conditions" point.

**Comment by Alexdavv** [comment]
> Don't understand the "halfway Conditions" point.

Here's [the discussion.](https://forums.ohdsi.org/t/condition-vs-measurement-domain-for-test-results/6128) Nobody even mentioned the "Obesvation" though.

**Comment by dimshitc** [comment]
Ok, so can we declare the rule:
**until it's not split to concept and value it is a condition.**?
or currently we have a mix anyway and some precoordinated entries are measurements? 
Yeah, I remember that discussion 
"why Anemia is a condition but decreased red blood cell count is measurement?"

**Comment by cgreich** [comment]
I see. So, the children to 4041436 are either Measurements with some result, or Procedures wtih some result. The former can turn back into these gray zone Conditions (Leukopenia). There are 2900 of them. We would need to:

- Split the Measurements. Should be easy, since many have a "Has interprets (SNOMED)" relationship to the measurement itself. 
- Map the Procedures to Procedures and throw away the result. 
- Decide whether to turn the Eosinophilias back into Conditions, or whether we turn them into "Eosinophiles - raised"

> declare the rule
That would work for a while. Problem is our "whiles" have a long life.

**Comment by m-khitrun** [comment]
Hello, @ericaVoss, @dimshitc, @cgreich

Please, be informed that these pre-coordinated measurements have been split and mapped to the respective measurements + their results as values. Pre-coordinated concepts that currently could not be mapped remain standard concepts in the Measurement domain.

Regards,
Masha.
