### ISSUE TITLE
Not able to upload ATHENA generated vocabularies using R script.

### ISSUE THREAD

**Issue by pratikcgd** [OHDSI/Vocabulary-v5.0#674]
Dear Team, 

I am not able to upload vocabularies on my DB (BigQuery) using the R script mentioned in this discussion. https://forums.ohdsi.org/t/the-r-package-to-upload-athena-generated-vocabulary-csv-files-into-db/7482

I am not facing any errors but the vocabs are not loading either. 

![image](https://user-images.githubusercontent.com/86762371/188511651-804f15b9-ce3a-4f69-9584-ef52f3b9aab3.png)

Can you please let me know if we can use **SQL using standard BQ commands?**

Thank you.

**Comment by mik-ohdsi** [comment]
So @pratikcgd - one lesson learned: first try the forums and only if it turns out that this is really an issue that need fixing and it cannot be solved with a little help from your fellow community members, come to the github issues and create one for tracking. I think Michael Kahn's [suggestion](https://forums.ohdsi.org/t/upload-vocabularies-csv-files-in-bigquery/17315/2) in the forum thread also sounds pretty exciting! Hope you have been helped! ~mik
