### ISSUE TITLE
Concept Relationship "Maps to" record for concepts 3661980 and 713860

### ISSUE THREAD

**Issue by boss-sam** [OHDSI/Vocabulary-v5.0#703]
**Is your feature request related to a problem? Please describe.**

We found that there is currently a gap when mapping between ICD10 and SNOMED using the concept_relationship table for covid-19 related concepts. In particular, there is no "maps to" record between 713860 and 3661980 which both represent concepts for "history of covid-19."

**Describe the solution you'd like**

Is it possible to add an additional "Maps to" record in the concept_relationship table between 3661980 and 713860?

**Describe alternatives you've considered**

We can manually map these for our internal processes in the short term, but flagging as it may help others with cross walking between the two vocabularies.

**Additional context**
N / A

**Comment by TinyRickC137** [comment]
Hello, @boss-sam 

Covid representation in OHDSI was quite a challenge in 2020. The community came out with the following [vocabulary release and instructions for the ETL process](https://github.com/OHDSI/Covid-19/wiki/Release). 

ICD10CM 713860 [Personal history of COVID-19](https://athena.ohdsi.org/search-terms/terms/713860) is mapped to [History of event](https://athena.ohdsi.org/search-terms/terms/1340204) (Maps to relationship) and [COVID-19](https://athena.ohdsi.org/search-terms/terms/37311061) (Maps to value relationship). According to ETL rules, one record in the Observation table with corresponding observation_concept_id and value_as_concept_id should be created. 

SNOMED 3661980 [History of SARS-CoV-2](https://athena.ohdsi.org/search-terms/terms/3661980) is mapped exactly the same way. 

Therefore, these two concepts are interconnected through the Standard concepts. The same way as other non-standard concepts. So you don't need to do any mappings: these concepts are already mapped.

Please, reach out to us if you still have any questions, otherwise, I will close the issue on Monday.
