### ISSUE TITLE
Unnecessary postcoordination in mapping to "Patient encounter procedure" and Maps to value to the procedure itself

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#716]
All those concepts mapped to [Patient encounter procedure](https://athena.ohdsi.org/search-terms/terms/4203722) have Maps to value to the exact procedure, while the "Patient encounter procedure" concept is useless. This way the procedure is lost in Observation table as value_as_concept_id.
I suggest to map these concepts directly to the procedure instead.

**Comment by Alexdavv** [comment]
Hi @dimshitc!

Do you have them in the data? What does the coding guidance say? Is it always the fact of the performed procedure? Or only planned? What if it wasn't performed because of the counterindications found?

The SNOMED's [Administrative procedures](https://athena.ohdsi.org/search-terms/terms/4033224) tend to be very simular, e.g. [Non-surgical biopsy - administration](https://athena.ohdsi.org/search-terms/terms/4065424).

Thoughts?

**Comment by dimshitc** [comment]
My understanding is that these codes are used when the reason of visit is one of the procedures listed, but they can't leave the diagnosis empty, so these codes were diagnosed.
here they don't even say "Encounter" for the most of the concept names
![image](https://user-images.githubusercontent.com/8568959/233606773-75f43f85-6512-45f6-a3dc-891cdb7ee1bf.png)
(I don't know why we have different names),
Can you check in a real data how these concepts related to an actual procedures?

**Comment by dimshitc** [comment]
Addressed here #996 as the community contribution
