### ISSUE TITLE
"Encounter for screening for COVID-19" potentially wrong mapping

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#724]
https://athena.ohdsi.org/search-terms/terms/713855 
I think this Maps to value will not work properly, users expect the result of a measurement in a value_as_concept_id, not a type of measurement

Also [Patient encounter procedure](https://athena.ohdsi.org/search-terms/terms/4203722) are mapped to "Patient encounter procedure" according to the current convention, so "Encounter for screening for COVID-19" is probably mapped inconsistently

**Comment by dimshitc** [comment]
Z11.4	Encounter for screening for human immunodeficiency virus [HIV]	Maps to value	171121004	HIV screening
Z11.4	Encounter for screening for human immunodeficiency virus [HIV]	Maps to	308335008	Patient encounter procedure

Z71.7	Human immunodeficiency virus [HIV] counseling	Maps to	308335008	Patient encounter procedure
Z71.7	Human immunodeficiency virus [HIV] counseling	Maps to value	313077009	Human immunodeficiency virus counseling

why don't you map these codes to procedures directly?
it seems to nice features when constructing HIV phenotypes. For example if I want to prove that Phenotype is correct, I would like to see these concepts in patient's timeline. 
Currently value_as_concept is not supported by Cohort Characterization directly.
So please fix these and other mappings of such kind

**Comment by Alexdavv** [comment]
Hi @dimshitc

> why don't you map these codes to procedures directly?

Which procedure? Encounter procedure or HIV screening?
Both are non-Standard when we're a step closer to clean vocabularies according to principles.


> it seems to nice features when constructing HIV phenotypes

Yeah, but it's modeled a while ago: pick [Viral screening](https://athena.ohdsi.org/search-terms/terms/4086918) or a step higher, and the value of the disease.


> these codes

May I ask why didn't you report them all in the original post?
We don't overhaul the entire use case if something small is reported. Users are much closer to the problem so we encourage to report in bulk.

> For example if I want to prove that Phenotype is correct, I would like to see these concepts in patient's timeline

Yeah, but don't use it as a disease/lab test phenotype. Not yet a test, many diseases are screened by a combination of other approaches.

> Currently value_as_concept is not supported by Cohort Characterization directly

Unfortunately, but at some point in time, OHDSI might consider it a requirement because we have a list of exclusions of things that cannot be pre-coordinated, so we split them gradually in vocabularies.

> So please fix these

But how exactly?

> other mappings of such kind

For me, it sounds like a small thing that would require lots of work. I don't think we'll be able to prioritize this unless somebody recognizes it as a community contribution effort done by themselves.

**Comment by dimshitc** [comment]
Why is it lots of work?
I can do the contribution
I will replace 'Maps to value' with 'Maps to', and deprecate original 'maps to' with 308335008 Patient encounter procedure,
so there will be 
Z71.7 Human immunodeficiency virus [HIV] counseling Maps to 313077009 Human immunodeficiency virus counseling.

Just let me know if it looks good to you and you will implement this fix, so my time will not be wasted.

> May I ask why didn't you report them all in the original post?
I was too lazy to look for all of them, same as now. 
my process currently is going through the therapeutic areas, not vocabulary specific problems.

**Comment by Alexdavv** [comment]
Because the entire use case(es) is not just 4 HIV concepts * 5 vocabularies. It's much more. Probably a couple of thousand. The task of finding them is already a piece of work - so it's not just you were too lazy, it's a lot of work. Unless you say you only care about HIV. But then it's a targeted community contribution, indeed. But it is better if we align on the conventions/approach first. Which still requires some investigation.

Still, cannot follow the proposal. If it's a screening, or a lab-test, etc we can't pre-coordinate because there's a decision and we already started splitting them.
For a counseling thing, there's no decision so far, but I believe it'll go the same way at some point in time.

Thoughts?

**Comment by dimshitc** [comment]
**1. get rid of Maps to 308335008 Patient encounter procedure - this is an idea of this post**
2. then you end up with Maps to 'HIV screening'. and then we can think if we need to postcoordinate it.
this is a side note:
Why do you postcoordinate the COVID screening thought? by putting the type of virus in value_as_concept_id.
In value_as_concept_id we expect the result of test, not a property of test.

**Comment by Alexdavv** [comment]
> 1. get rid of Maps to 308335008 Patient encounter procedure - this is an idea of this post

Agree.

> Why do you postcoordinate the COVID screening thought? by putting the type of virus in value_as_concept_id.

Because when the number of combinations is pretty much the entire Domain, we don't do that. Examples: [history of](https://athena.ohdsi.org/search-terms/terms/1340204), family history (not yet done but there's an agreement that a disease goes to the value), lab test results, allergies to drugs, need for vaccination, etc. [Here are](https://ohdsi.github.io/CommonDataModel/vocabulary.html) most of them.

Not the virus, the disease should go to the value.

> In value_as_concept_id we expect the result of test, not a property of test.

The screening is not necessarily a measurement/test. Could be a set of things including the interview and physical examination.
And you don't really expect the result of screening in this context. If the result is positive, there'll be a Standard disease concept in the Condition Domain/table. The negative result is a flavor of null.

**Comment by dimshitc** [comment]
Overhaul of these Encounter of, see here https://github.com/OHDSI/Vocabulary-v5.0/issues/996
