### ISSUE TITLE
Adding a number of NHS codes to the OMOP vocabulary  

### ISSUE THREAD

**Issue by solmazeradat** [OHDSI/Vocabulary-v5.0#794]
Hi, 

Hope you are well. 

As part of the Great Ormond Street Hospital (GOSH) OMOP project we have asked on the OHDSI forum for the following vocabularies to be added: 

Forum post: https://forums.ohdsi.org/t/mapping-nhs-ethnicity-codes/17332 (raised on 22/09/2022)
- NHS ETHIC Category - https://www.datadictionary.nhs.uk/data_elements/ethnic_category.html

Forum post: https://forums.ohdsi.org/t/request-to-add-nhs-vocabularies-admission-source-and-discharge-destination/17938/2 (Raised 22/12/2022)
- Admission Source - https://www.datadictionary.nhs.uk/data_elements/admission_source__hospital_provider_spell_.html?hl=admission%2Csource
- Discharge destination - https://www.datadictionary.nhs.uk/data_elements/discharge_destination_code__hospital_provider_spell_.html?hl=discharge%2Cdestination

As part of an agree action from the Vocabulary Subgroup team, I am planning on reaching out to the wider community to see if any other NHS codes could be also added. 

Thanks,
Solmaz

**Comment by cgreich** [comment]
@solmazeradat: Like already discussed in the Forum, we need to map Admission Source and Discharge Destination to the existing Visit concepts or to nothing, if it is outside healthcare. These will not become standard, unless they are needed because they don't exist yet. 

Reason it's taking time is we want to use this as an example for the external contribution process that is being set up.

**Comment by solmazeradat** [comment]
Thanks @cgreich . 

Yesterday during the vocabulary subgroup meeting, we discuss taking this example of adding NHS codes as a Use Case to aid in documenting the process on how to add a vocabulary to Athena. 

I have agreed to document the process and will be coming along to the vocabulary subgroup meeting moving forward to capture community input so we a clearer process is documented and shared with the community. 

Many thanks, Solmaz

**Comment by mik-ohdsi** [comment]
thank you @solmazeradat ,
attaching an Excel file illustrating that we will presumably need two vocabs for this or separate Admission and Discharge codes by concept_code as their codes are not always have the same meaning.
[Adm_Disch-Codes.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/11224511/Adm_Disch-Codes.xlsx)
@cgreich  -  we discussed in Teams and in the Vocabulary Subgroup that there might be some more NHS codesets that we should include that would otherwise block OMOP CDM adoption in UK beyond admission and discharge codes. Solmaz is meant to lead and facilitate this activity, collect the input and rally up troops that will prepare the material. If it turns out it is only Adm/Dis, even better.

**Comment by cgreich** [comment]
Not following.

Why is admission and discharge different? And why are we changing what we said we'd do a couple weeks ago? What is blocking?

**Comment by solmazeradat** [comment]
Thanks @mik-ohdsi and @cgreich. 

I will join tomorrow's meeting to provide an update on the progress on adding further NHS codes as part of this exercise. 
I did reach out again on a previous forum post about Adding NHS codes https://forums.ohdsi.org/t/nhs-anyone-here-converting-nhs-trust-level-data-to-omop-cdm/17356/7?u=solmaz.eradat and didn't see any further responses. 
Was thinking one idea might be to raise this topic in one of the community calls and that way might reach a wider audience? 

Thank you,
Solmaz

**Comment by solmazeradat** [comment]
Hi @mik-ohdsi and @cgreich , 

I have updated the Excel document that was shared with the admission and discharge codes and added the full list of NHS codes we are proposing to be added following further engagement with one other NHS hospital that mapped their data to the OMOP CDM. 

[ethnicity_admission_dischage_NHS.xlsx](https://github.com/OHDSI/Vocabulary-v5.0/files/11334778/ethnicity_admission_dischage_NHS.xlsx)

- **The first tab is a template** - we can update and change this as we map out the process of adding vocabularies. 
- **The red tabs** -  list of proposed codes being added. You will see that data partners can add links to the forum post, github issue and the link to the source code
- **The amber tab(s)** - captures the proposed source to standard mapping - could add notes and final review points if these where discussed as part of any further review step. 
-  Once the mapping has been agreed/signed off - create a green tab with the final mapping for each proposed code mapping and pass this over to the vocabulary development team? 

Happy to discuss this during the next vocabulary subgroup meeting and share my notes on the mapping process so far.

Thanks,
Solmaz

**Comment by solmazeradat** [comment]
Morning @aostropolets ,

Hope you are well.

Great present a couple of weeks ago on the vocabulary survey findings and the roadmap presentations 🙂. Amazing work! 

I saw you added the label "new vocab request" to this GitHub issue.  I wanted to check with you if there is anything further from our side you would like in getting the codes ready to be added to the OMOP vocabulary?

Many thanks,
Solmaz

**Comment by solmazeradat** [comment]
Hi @aostropolets - Just created a new issue based on the updated process for adding new vocabularies https://github.com/OHDSI/Vocabulary-v5.0/issues/843 

Thanks,
Solmaz
