### ISSUE TITLE
Consistency in classifying domains for measurements and observations

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/Vocabulary-v5.0#8]
Why is concept ‘Yes’ (4188539) a Measurement Value, and concept ‘No’ (4188539) an observation?

Same for ‘Normal’ (4069590) and ‘Abnormal’ (4135493), and for ‘+’ (4123508) and ‘++’ (4126673).

I would have expected these concepts to fall within the same domain (presumably Measurement)

**Comment by cgreich** [comment]
Patrick:

 

Your first question: Because of a glitch in the propagation of domains. Yes is a child of “Presence findings”, and No is a child of “Absence findings”. In the upcoming release it is all sorted. Both are domain “Meas Value”.

 

Your second question: Abnormal: Because the domain “Meas Value” is assigned to all children of 4135493 “Findings values”. While Normal is a child of 417476 “Normality findings”. Both will be in the domain “Spec Disease Status”

 

Dima and I did a fine-combed review. The number of these obvious blunders should be drastically down, now.

 

Thanks for the reports. Keep it coming.

 

C

**Comment by cgreich** [comment]
Fixed
