### ISSUE TITLE
please submit to SNOMED the hierarchy problem: Traumatic injury is not a parent of PTSD obviosly

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#801]
![image](https://user-images.githubusercontent.com/8568959/232451534-00cca49b-f9bb-47b7-abb3-81251223dc8f.png)

and this problem exists in the OMOP vocabulary of course as well

**Comment by TinyRickC137** [comment]
Submitted to Snomed

**Comment by TinyRickC137** [comment]
@dimshitc FYI
Their reply was: PTSD is the result of either physical or psychological trauma suffered by the affected individual.  As 417746004 |Traumatic injury (disorder)| is defined as solely due to a traumatic event, which can be either physical or psychological, it is not inconsistent to have PTSD classify as a subtype

**Comment by dimshitc** [comment]
thank you @TinyRickC137 
this is so wrong, PTSD is not a result of physical trauma, but a psychological trauma that can appear due to excessive pain or fear or disability after physical trauma.
Can you please reply to that email, including me, so I can step in?

**Comment by TinyRickC137** [comment]
Of course, just create a new ticket for them, because mine has been closed: 
https://ihtsdo.freshdesk.com/support/discussions/forums/247152

They were extremely fast with their reply. 
Since this is not an OMOP vocab issue, can I close it?

**Comment by dimshitc** [comment]
yes, sure, let me do it for you
