### ISSUE TITLE
Missing CPT4 Code (0174A) in Vocabulary

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Vocabulary-v5.0#842]
**Describe the problem in content or desired feature**
The CPT4 code, 0174A, is missing in the CONCEPT.csv file; however, the concept_id, [705253](https://athena.ohdsi.org/search-terms/terms/705253), is found in Athena as well as the CONCEPT_RELATIONSHIP.csv file. I have downloaded the vocabulary three times as different bundles and experienced the same issue of missing this CPT4 code in the concept file.

I found that the code was missing when running the cpt4.sh file.

**Comment by Alexdavv** [comment]
Hi @cukarthik!

Thank you for your feedback.
This is because of #799 request. This concept is [yet missing in the UMLS source](https://uts.nlm.nih.gov/uts/umls/searchResults?searchString=0174A&vocabulary=CPT) which OMOP users access through the cpt4.jar tool.
The most probable reason is that it was [released](https://www.ama-assn.org/system/files/cpt-assistant-guide-coronavirus-march-2023.pdf) (effective March 14, 2023) after the latest CPT4 update in the UMLS system or because it takes them some time to officially [rename](https://www.ama-assn.org/system/files/cpt-assistant-guide-coronavirus-may-2023.pdf) "booster" to "additional dose" concepts - the decision the CPT4 authors has recently made.

While we're trying to figure it out and get resolved, could you please modify the concept_name of this concept manually? It's widely publically available and at the moment is "	Immunization administration by intramuscular injection of severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) (coronavirus disease [COVID-19]) vaccine, mRNA-LNP, bivalent spike protein, preservative free, 3 mcg/0.2 mL dosage, diluent reconstitute".

So the query would be:
```
UPDATE concept
SET concept_name = 'Immunization administration by intramuscular injection of severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) (coronavirus disease [COVID-19]) vaccine, mRNA-LNP, bivalent spike protein, preservative free, 3 mcg/0.2 mL dosage, diluent reconstitute'
WHERE concept_id = 705253
;
```

**Comment by mseal-cherokeehealth** [comment]
concept_id of 705253 does not exist to run the update statement.
`SELECT COUNT(concept_id) AS ct FROM concept c WHERE c.concept_id = 705253;`
0

**Comment by Alexdavv** [comment]
You're right. It sits only in the concept_cpt4.csv file. Can you take it from there?

**Comment by mseal-cherokeehealth** [comment]
I will wait for [cukarthik](https://github.com/cukarthik) to reply on how he wants to handle this.

**Comment by Alexdavv** [comment]
Hi @cukarthik and @mseal-cherokeehealth!

Please request and download a new vocabulary bundle from Athena (could be cpt4 vocabulary only because nothing changed but cpt4.jar fine).
There's no need to rerun everything from scratch, you can just re-run a fixed cpt4.jar tool against the vocabulary tables you already have unpacked and processed by the previous version of the tool.

**Comment by mseal-cherokeehealth** [comment]
Thank you for the notification, but I am working on OMOP through AOU which decides when and what we download. We have to wait until the AOU team drops them to our buckets as everyone on AOU must run the same vocab as it is a centralized study, not federated as OMOP was designed for.

But again, thank you for your notification.

Mark Seal
Senior Data Analyst
Talbott, TN | (423) 714-2262
[smallCHSLogo2016Flat]

**Comment by cukarthik** [comment]
Thanks @Alexdavv! For some reason, I didn't get these notifications. I will test and confirm shortly.

**Comment by cukarthik** [comment]
Works. Thanks.
