### ISSUE TITLE
"Gleason Score 6" concept absent

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#847]
There's a concept
1634230	Gleason-Score-<=6	Gleason Score <=6
but no concept of "Gleason Score 6". 
Existing concept doesn't make sense, since Gleason 6 is the lowest grade possible.
Should I replace this concept by newly created "Gleason Score 6" concept? (via community contribution)
Or just rename the existing one?

**Comment by aostropolets** [comment]
If done through community contribution, it would be filling template 5, where you only need to specify concept_code, vocabulary_id and put new name in concept_name. I’d defer to others regarding the actual name :)

**Comment by TinyRickC137** [comment]
Wait a bit, technically there are scores < 6, even though practice changed since the 1960s
[proof](https://www.pcf.org/about-prostate-cancer/diagnosis-staging-prostate-cancer/gleason-score-isup-grade/)
So we ыгззщке these use cases
Gleason Score 6 falls under Gleason Score <=6 therefore I see no problem here

**Comment by dimshitc** [comment]
Ok, makes sense
