### ISSUE TITLE
Derived Value Standard Concept

### ISSUE THREAD

**Issue by cukarthik** [OHDSI/Vocabulary-v5.0#851]
# Instructions

**0. Create the initial issue.**

From what I can tell, I cannot find a standard TypeConcept that handles derived values. Specifically, we would like to populated BMI into our measurement table based on height and weight that is recorded in the EHR. There is [this concept_id](https://athena.ohdsi.org/search-terms/terms/45754907) from the old way of doing Type Concepts that is now non-standard. If there is no alternative, I would suggest making this code standard under the Type Concept vocabulary or [this LOINC code](https://athena.ohdsi.org/search-terms/terms/1028966).

**4. Upload the template.**

The suggested change is [here](https://docs.google.com/spreadsheets/d/1mghHEOFKk5Zo6ApDEIGX2fV5CPF5fQtT/edit?usp=share_link&ouid=107724688755655696497&rtpof=true&sd=true).

**Comment by aostropolets** [comment]
Thanks so much, Karthik, looks great! @Alexdavv do you happen to remember how type concepts were consolidated and if "Derived value" was not moved over to begin with?

**Comment by aostropolets** [comment]
While @Alexdavv is on vacation, I did some digging. Here's the post I found about consolidating types: 
https://forums.ohdsi.org/t/concept-type-consolidation-please-take-a-look/8306

As per [spreadsheet attached](https://docs.google.com/spreadsheets/d/16uOoZAZPsHwSGszWAuMCVcOupvbiOGbTvfGGpLpTnGY/edit#gid=0), Christian and the team suggest to map Derived value to Type Concept "Standard algorithm". @cukarthik would it work for you? If so, we should add this mapping instead of adding a new standard term.

**Comment by cukarthik** [comment]
I see. So derived should be mapped to [Standard Algorithm](https://athena.ohdsi.org/search-terms/terms/32880). I'm not sure if the name is clear to me. These algorithms might not be standard across a network. I'm partial to Derived Value or Algorthmic Derived Value  :)

**Comment by aostropolets** [comment]
Got it! Let's summon @cgreich here since he owns the spreadsheet. I don't have a strong opinion but suspect he might.

**Comment by cgreich** [comment]
We do need a definition list. Just like for the Visits. But "standard algorithm" means something you apply systematically, rather than making it up by hand one at a time (that would be "manual abstraction" which we haven't got, yet). Whether or not that is standard across the network doesn't matter. You wouldn't know that anyway.

**Comment by aostropolets** [comment]
I’m trying to figure out where we stand here. Do we still want to add Derived Value or do we want to enhance documentation and use Standard Algorithm? @cukarthik @cgreich

**Comment by aostropolets** [comment]
Documentation for Type Concept vocabulary was further adjusted to clarify the use of Standard Algorithm [here](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Vocab.-Type_Concept).
