### ISSUE TITLE
 Adding new Payer→ Source of Payment Typology (SOPT) mappings. 

### ISSUE THREAD

**Issue by PriyaDesai70** [OHDSI/Vocabulary-v5.0#888]
**Adding new Payer→ Source of Payment Typology (SOPT) mappings.** 
**Justification:**

1. For the payer table, the payer is defined as the entity that administers the transaction. The SOPT vocabulary is considered to be the Standard vocabulary for this concept type. There are 171 accepted concepts in Athena. 
2. We have mapped a large number of payers (frequently seen at Stanford Medicine) to their appropriate SOPT concepts which are standard and have used these mappings to populate our Payer_plan table. 
3. These mappings were reviewed by Michael Kallfelz in the Spring/Summer of 2022. Since many of these payers are national providers, we believe these mappings would be useful to the extended community. For example, thanks to ongoing work on the COST & PRICE tables with the common data model, several teams such as @onefact have expressed willingness to expand this initial mapping using public price transparency data from hospitals which often list tens to hundreds of payor names that can be condensed for an expanded vocabulary.
4.  The goal/hope is to stratify this information and identify if Persons have the same payer (though the name of the Payer is not necessary) as well as enable health economics and outcomes research using public hospital price transparency data and transparency in coverage data that has been aggregated by folks in the OHDSI network. For example, the COST/PRICE table (https://github.com/OHDSI/CommonDataModel/tree/payless_health) is being designed to use these mappings to enable this type of research for the OHDSI community. 

We are using Template 4 as this is a new vocabulary
**0. Create the initial issue.**

Please create the initial issue that briefly describes the content of intended contribution and rationale behind it. This will allow us to keep track of requests and connect you with other contributors who may be working on the same content.

**1. Read the documentation.**

Please familiarize yourself with the documentation [here](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Community-contribution) prior to initiating the submission.

**2. Choose the category of submission.**

Choose the category of your submission and download the corresponding template:

- Template 1: Add non-standard concept(s) to an existing vocabulay (with or without synonyms or mappings);
- Template 2: Add synonym(s) to existing concept(s);
- Template 3: Add mapping to existing concept(s);
- Template 4: Add new non-standard vocabulary (with or without mappings).

**3. Fill the template.**

Please dowload the corresponding template from [this folder](https://drive.google.com/drive/u/1/folders/1D7hSGKQkWgJCAKXDNOjfoFcnRca0-57w) and fill it. Instructions and examples are provided inside. If questions occurr use comments in the current issue to contact the Vocabulary Team. Make sure you filled the checklist!

**4. Upload the template.**

Please go to [this folder](https://drive.google.com/drive/u/1/folders/1wXB3CK08-sPa0EdyLlIL8jHaBkuH7k3g), create a subfolder with your contribution (name it as GitHubIssueNumber_ContributionName_YourName) and upload your contribution there.

**5. Reference the template in this issue.**

Please add the link to your submission herin this issue.

**6. See your contribution in the next release!**

'Add content' contributions are not reviewed by the Vocabulary Team and you generally can expect to see them in the next release if the submission is made at least 2 months prior to the release date.

**Comment by aostropolets** [comment]
Hi Priya,

As per the current consensus, the OHDSI Standardized Vocabularies contain vocabularies, terminologies and ontologies and not free-text strings/data from flowsheets/etc. Community Contribution page has the following note explaining this:
"Please note that community contribution concerns adding or modifying the content related to structured vocabularies (entities that have identifiers, standardized names, and external references). If you are interested in adding free-text content (such as strings from flowsheets), please contact us by creating a GitHub issue, coming to the Vocabulary WG call or the Healthcare Systems Special Interest WG call." 

In case of this contribution, it does not seem as a vocabulary, therefore it would not constitute community contribution. If it is a vocabulary, providing a link to it would be helpful.

Otherwise, please contact Melanie or HSSSI group for more details on how to contribute your free-text strings to a knowledge base she is creating.
