### ISSUE TITLE
92614 missing concepts from CONCEPT

### ISSUE THREAD

**Issue by rosemarybliss** [OHDSI/Vocabulary-v5.0#889]
Hello, it seems that there are missing concepts from the CONCEPT table. When looking for the concept_id_2 from the concept_relationship table in the actual concept table, they do not exist, however, they appear as concept codes. 

```
--The missing concepts from CONCEPT table:

SELECT *
FROM 
    CONCEPT_RELATIONSHIP
WHERE 
    CONCEPT_ID_2 
NOT IN 
    (SELECT SRC_CONCEPT_ID FROM CONCEPT);


--They appear as concept codes instead of concept IDs:

SELECT * 
FROM
    CONCEPT
WHERE
    CONCEPT_CODE
LIKE
'%2211582%';

```

Let me know if this an issue on my end. Thanks!

**Comment by TinyRickC137** [comment]
Hello, @rosemarybliss 

It seems like a problem on your side. I see only one concept in your latest query, and it is RxE concept from 2017. 

Any chance you are using `concept `and `concept_relationship `tables from different vocabulary versions? Any import errors?

**Comment by rosemarybliss** [comment]
Hmm, yes I also get the 2017 RxE concept with the second query but what about the first one? Do you get any concepts using the first query? That may be able to tell me if it's an import error. Thank you so much!

**Comment by TinyRickC137** [comment]
@rosemarybliss No, of course not. 

There are a whole level of [constraints](https://github.com/OHDSI/Vocabulary-v5.0/blob/master/working/DevV5_DDL.sql#L258) and QA to prevent this.

**Comment by cgreich** [comment]
@rosemarybliss:

> When looking for the concept_id_2 from the concept_relationship table in the actual concept table, they do not exist, 

As @TinyRickC137 said this is not possible because database constraints prevent that. Should do in your instance as well, if you installed the constraints. Looks like something might have gone wrong when loading the data. Can you check?

> however, they appear as concept codes.

That is sheer coincidence. The codes are created by the originators of the vocabulary while the IDs are OMOP-generated. Even if they by chance are the same that has no meaning.

**Comment by rosemarybliss** [comment]
@TinyRickC137 @cgreich 
Thank you both, it must be a loading issue on our part then. I will consult our team in that case and notify if we catch anything.

**Comment by TinyRickC137** [comment]
No problem, @rosemarybliss 

I will close this issue

**Comment by rosemarybliss** [comment]
@TinyRickC137 
Hello! Reaching back out with a small question to figure out this loading issue. It seems that along with our CONCEPT table, there was a separate table created called CONCEPT_CPT4. Is this intentional or does this signify our error? Is CPT4 supposed to be its own concept table? Thanks for your help.

**Comment by TinyRickC137** [comment]
No problem. 

CPT4 is EULA-required vocabulary, where EULA stands for End User License Agreement. We cannot distribute CPT4 freely to everyone like we are doing with other vocabularies, because first, your EULA needs to be checked. Therefore, to correctly process CP4 concepts, you need to use CPT4.bar script with API key you can get from UMLS.
