### ISSUE TITLE
Deprecated COVID concepts but still standard and maps to itself

### ISSUE THREAD

**Issue by xj2193** [OHDSI/Vocabulary-v5.0#921]
These COVID related concepts are found not valid since May 2023 but are still standard concepts. 
And the maps to relationship is mapping to itself.

1. [801235](https://athena.ohdsi.org/search-terms/terms/801235)
2. [704058](https://athena.ohdsi.org/search-terms/terms/704058)
3. [704059](https://athena.ohdsi.org/search-terms/terms/704059)

**Comment by TinyRickC137** [comment]
That's right, @xj2193 

We call them '[zombies](https://github.com/OHDSI/Vocabulary-v5.0/wiki/Standard-but-deprecated-(by-the-source)-%E2%80%9Czombie%E2%80%9D-concepts)'

In short, this is not a bug, but a feature of the vocabulary system. They can't be mapped with enough granularity, and they are deprecated by the source but still spotted very often in the data. That's why we turned them into Zombies - Standard and Valid, but validity dates are in the past.
