### ISSUE TITLE
Eosinophil count above reference range postcoordination is suboptimal

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Vocabulary-v5.0#977]
Same problem as #976.
Children of Eosinophilia are specified as precoordinated concepts, Unspecified Eosinophilia is defined through the Maps to + Maps to value

**Comment by m-khitrun** [comment]
Hello, @dimshitc 

Indeed, this 'Eosinophilia' concept is incorrectly mapped due to an erroneous replacement link. We will fix both the mapping and the replacement link. The good news is that this concept has never been active according to SNOMED sources so it can't affect any mapping.

Some old deprecated concepts are displayed with a blank left side in Athena, this bug was reported to the developers.

**Comment by Alexdavv** [comment]
https://github.com/OHDSI/Athena/issues/270

**Comment by TinyRickC137** [comment]
Let's discuss the issue in #976
